"""Modules for a simulation field and terrain generation."""

FIELD_SCALE = 64
FIELD_BASE_WIDTH = 8
FIELD_BASE_HEIGHT = 4

FIELD_WIDTH = FIELD_SCALE*FIELD_BASE_WIDTH
FIELD_HEIGHT = FIELD_SCALE*FIELD_BASE_HEIGHT + 1

FIELD_CIRCUMFERENCE = 40_000  # km

CELL_DIAMETER = 1000*FIELD_CIRCUMFERENCE/(2*FIELD_HEIGHT)  # m

SEA_LEVEL = 0.0  # m

ELEV_MEAN = 0.0   # m
ELEV_SD = 1_000.0  # m
